package net.regions_unexplored.config;

import net.regions_unexplored.internal.config.Config;
import net.regions_unexplored.internal.config.ConfigValue;
import net.regions_unexplored.internal.config.annotation.ConfigOption;

public class RuCommonConfig extends Config {
    @ConfigOption(category = "features")
    public static final ConfigValue<Boolean> USE_LOGS_FOR_BRANCHES = bool(false);

    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_ALPHA_GROVE = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_ARID_MOUNTAINS = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_ASHEN_WOODLAND = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_AUTUMNAL_MAPLE_FOREST = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_BAMBOO_FOREST = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_BAOBAB_SAVANNA = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_BARLEY_FIELDS = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_BAYOU = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_BLACKWOOD_TAIGA = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_BOREAL_TAIGA = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_CHALK_CLIFFS = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_CLOVER_PLAINS = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_COLD_BOREAL_TAIGA = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_COLD_DECIDUOUS_FOREST = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_COLD_RIVER = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_DECIDUOUS_FOREST = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_DRY_BUSHLAND = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_EUCALYPTUS_FOREST = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_FEN = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_FLOWER_FIELDS = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_FROZEN_PINE_TAIGA = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_FROZEN_TUNDRA = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_FUNGAL_FEN = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_GOLDEN_BOREAL_TAIGA = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_GRASSLAND = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_GRASSY_BEACH = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_GRAVEL_BEACH = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_HIGHLAND_FIELDS = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_HYACINTH_DEEPS = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_ICY_DESERT = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_ICY_HEIGHTS = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_JOSHUA_DESERT = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_MAGNOLIA_WOODLAND = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_MAPLE_FOREST = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_MARSH = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_MAUVE_HILLS = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_MEADOW = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_MOUNTAINS = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_MUDDY_RIVER = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_OLD_GROWTH_BAYOU = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_ORCHARD = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_OUTBACK = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_PINE_SLOPES = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_PINE_TAIGA = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_POPPY_FIELDS = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_PRAIRIE = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_PUMPKIN_FIELDS = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_RAINFOREST = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_ROCKY_REEF = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_REDWOODS = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_SAGUARO_DESERT = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_SHRUBLAND = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_SILVER_BIRCH_FOREST = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_SPARSE_RAINFOREST = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_SPARSE_REDWOODS = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_SPIRES = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_STEPPE = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_TEMPERATE_GROVE = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_TOWERING_CLIFFS = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_TROPICAL_RIVER = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_TROPICS = bool(true);
    @ConfigOption(category = "overworld_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_WILLOW_FOREST = bool(true);

    @ConfigOption(category = "overworld_cave_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_ANCIENT_DELTA = bool(true);
    @ConfigOption(category = "overworld_cave_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_BIOSHROOM_CAVES = bool(true);
    @ConfigOption(category = "overworld_cave_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_PRISMACHASM = bool(true);
    @ConfigOption(category = "overworld_cave_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_REDSTONE_CAVES = bool(true);
    @ConfigOption(category = "overworld_cave_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_SCORCHING_CAVES = bool(true);

    @ConfigOption(category = "nether_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_BLACKSTONE_BASIN = bool(true);
    @ConfigOption(category = "nether_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_GLISTERING_MEADOW = bool(true);
    @ConfigOption(category = "nether_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_INFERNAL_HOLT = bool(true);
    @ConfigOption(category = "nether_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_MYCOTOXIC_UNDERGROWTH = bool(true);
    @ConfigOption(category = "nether_biome_toggles")
    public static final ConfigValue<Boolean> TOGGLE_REDSTONE_ABYSS = bool(true);

    @ConfigOption(category = "worldgen_surface_rules")
    public static final ConfigValue<Boolean> TOGGLE_CUSTOM_DIRTS = bool(true);
}