package net.regions_unexplored.block;

import net.regions_unexplored.block.RuBlocks;

import static net.regions_unexplored.util.BlockCompatUtil.registerFlammableBlock;

public class FlammableBlocks {
    public static void setup() {
        /*-----------------CAVE_BLOCKS-----------------*/
        //PRISMA_BLOCKS
        registerFlammableBlock(RuBlocks.PRISMOSS_SPROUT, 60, 100);

        registerFlammableBlock(RuBlocks.CORPSE_FLOWER, 60, 100);
        registerFlammableBlock(RuBlocks.BLADED_GRASS, 60, 100);
        registerFlammableBlock(RuBlocks.BLADED_TALL_GRASS, 60, 100);
        registerFlammableBlock(RuBlocks.DROPLEAF, 60, 100);
        registerFlammableBlock(RuBlocks.DROPLEAF_PLANT, 60, 100);
        registerFlammableBlock(RuBlocks.DUSKMELON, 60, 100);
        registerFlammableBlock(RuBlocks.DUSKTRAP, 60, 100);
        /*-----------------PLANTS-----------------*/
        //GRASS_BLOCKS
        registerFlammableBlock(RuBlocks.DEAD_STEPPE_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.FROZEN_GRASS, 60, 100);
        registerFlammableBlock(RuBlocks.MEDIUM_GRASS, 60, 100);
        registerFlammableBlock(RuBlocks.SANDY_GRASS, 60, 100);
        registerFlammableBlock(RuBlocks.SMALL_DESERT_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.STEPPE_GRASS, 60, 100);
        registerFlammableBlock(RuBlocks.STEPPE_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.STONE_BUD, 60, 100);
        //TALL_GRASS_BLOCKS
        registerFlammableBlock(RuBlocks.ELEPHANT_EAR, 60, 100);
        registerFlammableBlock(RuBlocks.SANDY_TALL_GRASS, 60, 100);
        registerFlammableBlock(RuBlocks.STEPPE_TALL_GRASS, 60, 100);
        registerFlammableBlock(RuBlocks.WINDSWEPT_GRASS, 60, 100);
        //FLOWERS
        registerFlammableBlock(RuBlocks.ALPHA_DANDELION, 60, 100);
        registerFlammableBlock(RuBlocks.ALPHA_ROSE, 60, 100);
        registerFlammableBlock(RuBlocks.ASTER, 60, 100);
        registerFlammableBlock(RuBlocks.BLEEDING_HEART, 60, 100);
        registerFlammableBlock(RuBlocks.BLUE_LUPINE, 60, 100);
        registerFlammableBlock(RuBlocks.DAISY, 60, 100);
        registerFlammableBlock(RuBlocks.FELICIA_DAISY, 60, 100);
        registerFlammableBlock(RuBlocks.FIREWEED, 60, 100);
        registerFlammableBlock(RuBlocks.HIBISCUS, 60, 100);
        registerFlammableBlock(RuBlocks.HYSSOP, 60, 100);
        registerFlammableBlock(RuBlocks.MALLOW, 60, 100);
        registerFlammableBlock(RuBlocks.PINK_LUPINE, 60, 100);
        registerFlammableBlock(RuBlocks.POPPY_BUSH, 60, 100);
        registerFlammableBlock(RuBlocks.SALMON_POPPY_BUSH, 60, 100);
        registerFlammableBlock(RuBlocks.PURPLE_LUPINE, 60, 100);
        registerFlammableBlock(RuBlocks.RED_LUPINE, 60, 100);
        registerFlammableBlock(RuBlocks.WARATAH, 60, 100);
        registerFlammableBlock(RuBlocks.WHITE_TRILLIUM, 60, 100);
        registerFlammableBlock(RuBlocks.WILTING_TRILLIUM, 60, 100);
        registerFlammableBlock(RuBlocks.YELLOW_LUPINE, 60, 100);

        registerFlammableBlock(RuBlocks.ORANGE_CONEFLOWER, 60, 100);
        registerFlammableBlock(RuBlocks.PURPLE_CONEFLOWER, 60, 100);
        registerFlammableBlock(RuBlocks.CLOVER, 60, 100);

        registerFlammableBlock(RuBlocks.BLUE_MAGNOLIA_FLOWERS, 60, 100);
        registerFlammableBlock(RuBlocks.PINK_MAGNOLIA_FLOWERS, 60, 100);
        registerFlammableBlock(RuBlocks.WHITE_MAGNOLIA_FLOWERS, 60, 100);
        //SNOWBELLE
        registerFlammableBlock(RuBlocks.RED_SNOWBELLE, 60, 100);
        registerFlammableBlock(RuBlocks.ORANGE_SNOWBELLE, 60, 100);
        registerFlammableBlock(RuBlocks.YELLOW_SNOWBELLE, 60, 100);
        registerFlammableBlock(RuBlocks.LIME_SNOWBELLE, 60, 100);
        registerFlammableBlock(RuBlocks.GREEN_SNOWBELLE, 60, 100);
        registerFlammableBlock(RuBlocks.CYAN_SNOWBELLE, 60, 100);
        registerFlammableBlock(RuBlocks.LIGHT_BLUE_SNOWBELLE, 60, 100);
        registerFlammableBlock(RuBlocks.BLUE_SNOWBELLE, 60, 100);
        registerFlammableBlock(RuBlocks.PURPLE_SNOWBELLE, 60, 100);
        registerFlammableBlock(RuBlocks.MAGENTA_SNOWBELLE, 60, 100);
        registerFlammableBlock(RuBlocks.PINK_SNOWBELLE, 60, 100);
        registerFlammableBlock(RuBlocks.BROWN_SNOWBELLE, 60, 100);
        registerFlammableBlock(RuBlocks.WHITE_SNOWBELLE, 60, 100);
        registerFlammableBlock(RuBlocks.LIGHT_GRAY_SNOWBELLE, 60, 100);
        registerFlammableBlock(RuBlocks.GRAY_SNOWBELLE, 60, 100);
        registerFlammableBlock(RuBlocks.BLACK_SNOWBELLE, 60, 100);

        registerFlammableBlock(RuBlocks.MAPLE_LEAF_PILE, 60, 100);
        registerFlammableBlock(RuBlocks.RED_MAPLE_LEAF_PILE, 60, 100);
        registerFlammableBlock(RuBlocks.ORANGE_MAPLE_LEAF_PILE, 60, 100);
        registerFlammableBlock(RuBlocks.SILVER_BIRCH_LEAF_PILE, 60, 100);
        registerFlammableBlock(RuBlocks.ENCHANTED_BIRCH_LEAF_PILE, 60, 100);
        //TALL_PLANTS
        registerFlammableBlock(RuBlocks.MEADOW_SAGE, 60, 100);
        registerFlammableBlock(RuBlocks.BARLEY, 60, 100);
        registerFlammableBlock(RuBlocks.CATTAIL, 60, 100);
        registerFlammableBlock(RuBlocks.TASSEL, 60, 100);
        registerFlammableBlock(RuBlocks.TSUBAKI, 60, 100);
        registerFlammableBlock(RuBlocks.DAY_LILY, 60, 100);
        //SAPLINGS
        registerFlammableBlock(RuBlocks.ALPHA_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.APPLE_OAK_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.BAMBOO_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.BAOBAB_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.BLACKWOOD_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.CACTUS_FLOWER, 60, 100);
        registerFlammableBlock(RuBlocks.CYPRESS_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.EUCALYPTUS_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.FLOWERING_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.GOLDEN_LARCH_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.JOSHUA_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.KAPOK_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.LARCH_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.MAGNOLIA_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.MAPLE_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.MAUVE_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.ORANGE_MAPLE_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.PALM_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.PINE_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.BLUE_MAGNOLIA_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.PINK_MAGNOLIA_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.REDWOOD_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.RED_MAPLE_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.ENCHANTED_BIRCH_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.SILVER_BIRCH_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.SMALL_OAK_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.SOCOTRA_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.WHITE_MAGNOLIA_SAPLING, 60, 100);
        registerFlammableBlock(RuBlocks.WILLOW_SAPLING, 60, 100);
        //SHRUBS
        registerFlammableBlock(RuBlocks.ACACIA_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.BAOBAB_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.BIRCH_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.BLACKWOOD_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.CHERRY_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.CYPRESS_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.DARK_OAK_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.EUCALYPTUS_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.FLOWERING_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.GOLDEN_LARCH_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.JOSHUA_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.JUNGLE_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.KAPOK_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.LARCH_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.MAGNOLIA_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.MANGROVE_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.MAPLE_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.MAUVE_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.OAK_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.ORANGE_MAPLE_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.PALM_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.PINE_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.BLUE_MAGNOLIA_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.PINK_MAGNOLIA_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.REDWOOD_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.RED_MAPLE_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.ENCHANTED_BIRCH_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.SILVER_BIRCH_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.SOCOTRA_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.SPRUCE_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.WHITE_MAGNOLIA_SHRUB, 60, 100);
        registerFlammableBlock(RuBlocks.WILLOW_SHRUB, 60, 100);
        //MUSHROOMS
        registerFlammableBlock(RuBlocks.BLUE_BIOSHROOM, 30, 60);
        registerFlammableBlock(RuBlocks.GREEN_BIOSHROOM, 30, 60);
        registerFlammableBlock(RuBlocks.PINK_BIOSHROOM, 30, 60);
        registerFlammableBlock(RuBlocks.TALL_BLUE_BIOSHROOM, 30, 60);
        registerFlammableBlock(RuBlocks.TALL_GREEN_BIOSHROOM, 30, 60);
        registerFlammableBlock(RuBlocks.TALL_PINK_BIOSHROOM, 30, 60);

        registerFlammableBlock(RuBlocks.BARREL_CACTUS, 60, 100);
        registerFlammableBlock(RuBlocks.CAVE_HYSSOP, 60, 100);
        registerFlammableBlock(RuBlocks.DUCKWEED, 60, 100);
        registerFlammableBlock(RuBlocks.SPANISH_MOSS, 15, 100);
        registerFlammableBlock(RuBlocks.SPANISH_MOSS_PLANT, 15, 100);
        registerFlammableBlock(RuBlocks.KAPOK_VINES, 15, 100);
        registerFlammableBlock(RuBlocks.KAPOK_VINES_PLANT, 15, 100);
        registerFlammableBlock(RuBlocks.FLOWERING_LILY_PAD, 15, 100);
        registerFlammableBlock(RuBlocks.GIANT_LILY_PAD, 15, 100);
        //FOOD_PLANT_BLOCKS
        registerFlammableBlock(RuBlocks.SALMONBERRY_BUSH, 60, 100);
        /*-----------------PLANT_BLOCKS-----------------*/
        //MUSHROOMS
        registerFlammableBlock(RuBlocks.BLUE_BIOSHROOM_BLOCK, 30, 60);
        registerFlammableBlock(RuBlocks.GLOWING_BLUE_BIOSHROOM_BLOCK, 30, 60);
        registerFlammableBlock(RuBlocks.GREEN_BIOSHROOM_BLOCK, 30, 60);
        registerFlammableBlock(RuBlocks.GLOWING_GREEN_BIOSHROOM_BLOCK, 30, 60);
        registerFlammableBlock(RuBlocks.PINK_BIOSHROOM_BLOCK, 30, 60);
        registerFlammableBlock(RuBlocks.GLOWING_PINK_BIOSHROOM_BLOCK, 30, 60);
        //BAMBOO
        registerFlammableBlock(RuBlocks.BAMBOO_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_BAMBOO_LOG, 5, 5);
        //OAK_LOG
        registerFlammableBlock(RuBlocks.SMALL_OAK_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_SMALL_OAK_LOG, 5, 5);
        //CACTUS
        registerFlammableBlock(RuBlocks.SAGUARO_CACTUS, 5, 5);

        /*-----------------LEAVES-----------------*/
        registerFlammableBlock(RuBlocks.ALPHA_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.APPLE_OAK_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.BAMBOO_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.BAOBAB_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.BLACKWOOD_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.MAGNOLIA_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.CYPRESS_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.EUCALYPTUS_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.FLOWERING_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.GOLDEN_LARCH_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.JOSHUA_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.KAPOK_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.LARCH_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.MAPLE_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.MAUVE_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.ORANGE_MAPLE_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.PALM_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.PINE_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.BLUE_MAGNOLIA_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.PINK_MAGNOLIA_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.REDWOOD_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.RED_MAPLE_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.SMALL_OAK_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.SILVER_BIRCH_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.SOCOTRA_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.ENCHANTED_BIRCH_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.WHITE_MAGNOLIA_LEAVES, 30, 60);
        registerFlammableBlock(RuBlocks.WILLOW_LEAVES, 30, 60);

        /*-----------------BRANCHES-----------------*/
        registerFlammableBlock(RuBlocks.ACACIA_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.BAOBAB_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.BIRCH_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.BLACKWOOD_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.MAGNOLIA_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.CYPRESS_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.CHERRY_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.DARK_OAK_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.EUCALYPTUS_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.JOSHUA_BEARD, 30, 100);
        registerFlammableBlock(RuBlocks.JUNGLE_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.KAPOK_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.LARCH_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.MANGROVE_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.MAPLE_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.MAUVE_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.OAK_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.PALM_BEARD, 30, 100);
        registerFlammableBlock(RuBlocks.PINE_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.REDWOOD_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.SILVER_BIRCH_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.SOCOTRA_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.SPRUCE_BRANCH, 30, 100);
        registerFlammableBlock(RuBlocks.WILLOW_BRANCH, 30, 100);
        /*-----------------WOOD_TYPES-----------------*/
        //SILVER_BIRCH_BLOCKS
        registerFlammableBlock(RuBlocks.SILVER_BIRCH_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.SILVER_BIRCH_WOOD, 5, 5);
        //ALPHA_BLOCKS
        registerFlammableBlock(RuBlocks.ALPHA_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.ALPHA_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.ALPHA_STAIRS, 5, 20);
        //BAOBAB_BLOCKS
        registerFlammableBlock(RuBlocks.BAOBAB_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_BAOBAB_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.BAOBAB_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_BAOBAB_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.BAOBAB_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.BAOBAB_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.BAOBAB_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.BAOBAB_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.BAOBAB_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.BAOBAB_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.BAOBAB_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.BAOBAB_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.BAOBAB_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.BAOBAB_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.BAOBAB_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.BAOBAB_WALL_HANGING_SIGN, 5, 20);
        //BLACKWOOD_BLOCKS
        registerFlammableBlock(RuBlocks.BLACKWOOD_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_BLACKWOOD_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.BLACKWOOD_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_BLACKWOOD_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.BLACKWOOD_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.BLACKWOOD_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.BLACKWOOD_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.BLACKWOOD_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.BLACKWOOD_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.BLACKWOOD_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.BLACKWOOD_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.BLACKWOOD_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.BLACKWOOD_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.BLACKWOOD_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.BLACKWOOD_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.BLACKWOOD_WALL_HANGING_SIGN, 5, 20);
        //BLUE_BIOSHROOM_BLOCKS
        registerFlammableBlock(RuBlocks.BLUE_BIOSHROOM_STEM, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_BLUE_BIOSHROOM_STEM, 5, 5);
        registerFlammableBlock(RuBlocks.BLUE_BIOSHROOM_HYPHAE, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_BLUE_BIOSHROOM_HYPHAE, 5, 5);
        registerFlammableBlock(RuBlocks.BLUE_BIOSHROOM_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.BLUE_BIOSHROOM_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.BLUE_BIOSHROOM_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.BLUE_BIOSHROOM_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.BLUE_BIOSHROOM_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.BLUE_BIOSHROOM_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.BLUE_BIOSHROOM_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.BLUE_BIOSHROOM_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.BLUE_BIOSHROOM_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.BLUE_BIOSHROOM_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.BLUE_BIOSHROOM_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.BLUE_BIOSHROOM_WALL_HANGING_SIGN, 5, 20);
        //CYPRESS_BLOCKS
        registerFlammableBlock(RuBlocks.CYPRESS_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_CYPRESS_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.CYPRESS_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_CYPRESS_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.CYPRESS_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.CYPRESS_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.CYPRESS_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.CYPRESS_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.CYPRESS_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.CYPRESS_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.CYPRESS_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.CYPRESS_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.CYPRESS_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.CYPRESS_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.CYPRESS_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.CYPRESS_WALL_HANGING_SIGN, 5, 20);
        //EUCALYPTUS_BLOCKS
        registerFlammableBlock(RuBlocks.EUCALYPTUS_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_EUCALYPTUS_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.EUCALYPTUS_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_EUCALYPTUS_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.EUCALYPTUS_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.EUCALYPTUS_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.EUCALYPTUS_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.EUCALYPTUS_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.EUCALYPTUS_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.EUCALYPTUS_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.EUCALYPTUS_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.EUCALYPTUS_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.EUCALYPTUS_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.EUCALYPTUS_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.EUCALYPTUS_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.EUCALYPTUS_WALL_HANGING_SIGN, 5, 20);
        //GREEN_BIOSHROOM_BLOCKS
        registerFlammableBlock(RuBlocks.GREEN_BIOSHROOM_STEM, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_GREEN_BIOSHROOM_STEM, 5, 5);
        registerFlammableBlock(RuBlocks.GREEN_BIOSHROOM_HYPHAE, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_GREEN_BIOSHROOM_HYPHAE, 5, 5);
        registerFlammableBlock(RuBlocks.GREEN_BIOSHROOM_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.GREEN_BIOSHROOM_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.GREEN_BIOSHROOM_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.GREEN_BIOSHROOM_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.GREEN_BIOSHROOM_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.GREEN_BIOSHROOM_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.GREEN_BIOSHROOM_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.GREEN_BIOSHROOM_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.GREEN_BIOSHROOM_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.GREEN_BIOSHROOM_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.GREEN_BIOSHROOM_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.GREEN_BIOSHROOM_WALL_HANGING_SIGN, 5, 20);
        //JOSHUA_BLOCKS
        registerFlammableBlock(RuBlocks.JOSHUA_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_JOSHUA_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.JOSHUA_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_JOSHUA_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.JOSHUA_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.JOSHUA_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.JOSHUA_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.JOSHUA_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.JOSHUA_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.JOSHUA_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.JOSHUA_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.JOSHUA_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.JOSHUA_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.JOSHUA_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.JOSHUA_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.JOSHUA_WALL_HANGING_SIGN, 5, 20);
        //KAPOK_BLOCKS
        registerFlammableBlock(RuBlocks.KAPOK_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_KAPOK_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.KAPOK_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_KAPOK_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.KAPOK_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.KAPOK_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.KAPOK_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.KAPOK_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.KAPOK_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.KAPOK_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.KAPOK_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.KAPOK_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.KAPOK_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.KAPOK_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.KAPOK_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.KAPOK_WALL_HANGING_SIGN, 5, 20);
        //LARCH_BLOCKS
        registerFlammableBlock(RuBlocks.LARCH_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_LARCH_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.LARCH_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_LARCH_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.LARCH_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.LARCH_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.LARCH_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.LARCH_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.LARCH_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.LARCH_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.LARCH_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.LARCH_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.LARCH_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.LARCH_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.LARCH_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.LARCH_WALL_HANGING_SIGN, 5, 20);
        //MAGNOLIA_BLOCKS
        registerFlammableBlock(RuBlocks.MAGNOLIA_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_MAGNOLIA_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.MAGNOLIA_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_MAGNOLIA_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.MAGNOLIA_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.MAGNOLIA_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.MAGNOLIA_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.MAGNOLIA_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.MAGNOLIA_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.MAGNOLIA_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.MAGNOLIA_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.MAGNOLIA_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.MAGNOLIA_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.MAGNOLIA_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.MAGNOLIA_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.MAGNOLIA_WALL_HANGING_SIGN, 5, 20);
        //MAPLE_BLOCKS
        registerFlammableBlock(RuBlocks.MAPLE_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_MAPLE_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.MAPLE_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_MAPLE_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.MAPLE_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.MAPLE_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.MAPLE_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.MAPLE_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.MAPLE_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.MAPLE_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.MAPLE_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.MAPLE_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.MAPLE_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.MAPLE_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.MAPLE_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.MAPLE_WALL_HANGING_SIGN, 5, 20);
        //MAUVE_BLOCKS
        registerFlammableBlock(RuBlocks.MAUVE_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_MAUVE_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.MAUVE_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_MAUVE_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.MAUVE_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.MAUVE_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.MAUVE_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.MAUVE_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.MAUVE_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.MAUVE_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.MAUVE_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.MAUVE_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.MAUVE_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.MAUVE_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.MAUVE_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.MAUVE_WALL_HANGING_SIGN, 5, 20);
        //PALM_BLOCKS
        registerFlammableBlock(RuBlocks.PALM_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_PALM_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.PALM_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_PALM_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.PALM_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.PALM_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.PALM_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.PALM_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.PALM_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.PALM_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.PALM_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.PALM_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.PALM_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.PALM_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.PALM_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.PALM_WALL_HANGING_SIGN, 5, 20);
        //PINE_BLOCKS
        registerFlammableBlock(RuBlocks.PINE_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_PINE_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.PINE_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_PINE_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.PINE_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.PINE_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.PINE_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.PINE_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.PINE_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.PINE_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.PINE_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.PINE_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.PINE_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.PINE_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.PINE_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.PINE_WALL_HANGING_SIGN, 5, 20);
        //PINK_BIOSHROOM_BLOCKS
        registerFlammableBlock(RuBlocks.PINK_BIOSHROOM_STEM, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_PINK_BIOSHROOM_STEM, 5, 5);
        registerFlammableBlock(RuBlocks.PINK_BIOSHROOM_HYPHAE, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_PINK_BIOSHROOM_HYPHAE, 5, 5);
        registerFlammableBlock(RuBlocks.PINK_BIOSHROOM_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.PINK_BIOSHROOM_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.PINK_BIOSHROOM_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.PINK_BIOSHROOM_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.PINK_BIOSHROOM_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.PINK_BIOSHROOM_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.PINK_BIOSHROOM_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.PINK_BIOSHROOM_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.PINK_BIOSHROOM_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.PINK_BIOSHROOM_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.PINK_BIOSHROOM_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.PINK_BIOSHROOM_WALL_HANGING_SIGN, 5, 20);
        //REDWOOD_BLOCKS
        registerFlammableBlock(RuBlocks.REDWOOD_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_REDWOOD_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.REDWOOD_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_REDWOOD_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.REDWOOD_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.REDWOOD_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.REDWOOD_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.REDWOOD_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.REDWOOD_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.REDWOOD_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.REDWOOD_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.REDWOOD_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.REDWOOD_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.REDWOOD_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.REDWOOD_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.REDWOOD_WALL_HANGING_SIGN, 5, 20);
        //SOCOTRA_BLOCKS
        registerFlammableBlock(RuBlocks.SOCOTRA_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_SOCOTRA_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.SOCOTRA_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_SOCOTRA_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.SOCOTRA_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.SOCOTRA_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.SOCOTRA_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.SOCOTRA_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.SOCOTRA_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.SOCOTRA_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.SOCOTRA_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.SOCOTRA_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.SOCOTRA_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.SOCOTRA_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.SOCOTRA_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.SOCOTRA_WALL_HANGING_SIGN, 5, 20);
        //WILLOW_BLOCKS
        registerFlammableBlock(RuBlocks.WILLOW_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_WILLOW_LOG, 5, 5);
        registerFlammableBlock(RuBlocks.WILLOW_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.STRIPPED_WILLOW_WOOD, 5, 5);
        registerFlammableBlock(RuBlocks.WILLOW_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.WILLOW_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.WILLOW_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.WILLOW_FENCE, 5, 20);
        registerFlammableBlock(RuBlocks.WILLOW_DOOR, 5, 20);
        registerFlammableBlock(RuBlocks.WILLOW_FENCE_GATE, 5, 20);
        registerFlammableBlock(RuBlocks.WILLOW_TRAPDOOR, 5, 20);
        registerFlammableBlock(RuBlocks.WILLOW_PRESSURE_PLATE, 5, 20);
        registerFlammableBlock(RuBlocks.WILLOW_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.WILLOW_WALL_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.WILLOW_HANGING_SIGN, 5, 20);
        registerFlammableBlock(RuBlocks.WILLOW_WALL_HANGING_SIGN, 5, 20);

        /*-----------------PAINTED PLANKS-----------------*/
        //PLANKS
        registerFlammableBlock(RuBlocks.RED_PAINTED_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.ORANGE_PAINTED_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.YELLOW_PAINTED_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.LIME_PAINTED_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.GREEN_PAINTED_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.CYAN_PAINTED_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.LIGHT_BLUE_PAINTED_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.BLUE_PAINTED_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.PURPLE_PAINTED_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.MAGENTA_PAINTED_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.PINK_PAINTED_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.BROWN_PAINTED_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.WHITE_PAINTED_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.LIGHT_GRAY_PAINTED_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.GRAY_PAINTED_PLANKS, 5, 20);
        registerFlammableBlock(RuBlocks.BLACK_PAINTED_PLANKS, 5, 20);
        //STAIRS
        registerFlammableBlock(RuBlocks.RED_PAINTED_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.ORANGE_PAINTED_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.YELLOW_PAINTED_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.LIME_PAINTED_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.GREEN_PAINTED_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.CYAN_PAINTED_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.LIGHT_BLUE_PAINTED_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.BLUE_PAINTED_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.PURPLE_PAINTED_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.MAGENTA_PAINTED_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.PINK_PAINTED_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.BROWN_PAINTED_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.WHITE_PAINTED_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.LIGHT_GRAY_PAINTED_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.GRAY_PAINTED_STAIRS, 5, 20);
        registerFlammableBlock(RuBlocks.BLACK_PAINTED_STAIRS, 5, 20);
        //SLABS
        registerFlammableBlock(RuBlocks.RED_PAINTED_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.ORANGE_PAINTED_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.YELLOW_PAINTED_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.LIME_PAINTED_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.GREEN_PAINTED_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.CYAN_PAINTED_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.LIGHT_BLUE_PAINTED_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.BLUE_PAINTED_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.PURPLE_PAINTED_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.MAGENTA_PAINTED_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.PINK_PAINTED_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.BROWN_PAINTED_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.WHITE_PAINTED_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.LIGHT_GRAY_PAINTED_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.GRAY_PAINTED_SLAB, 5, 20);
        registerFlammableBlock(RuBlocks.BLACK_PAINTED_SLAB, 5, 20);
    }
}
