package net.regions_unexplored.registry;

import java.util.function.Supplier;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.level.levelgen.feature.Feature;
import net.minecraft.world.level.levelgen.feature.configurations.ColumnFeatureConfiguration;
import net.minecraft.world.level.levelgen.feature.configurations.FeatureConfiguration;
import net.minecraft.world.level.levelgen.feature.configurations.MultifaceGrowthConfiguration;
import net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration;
import net.minecraft.world.level.levelgen.feature.configurations.ProbabilityFeatureConfiguration;
import net.minecraft.world.level.levelgen.feature.configurations.VegetationPatchConfiguration;
import net.regions_unexplored.platform.Registar;
import net.regions_unexplored.world.level.feature.AirMultifaceGrowthFeature;
import net.regions_unexplored.world.level.feature.AshVentFeature;
import net.regions_unexplored.world.level.feature.BasaltBlobFeature;
import net.regions_unexplored.world.level.feature.FallenBlobTreeFeature;
import net.regions_unexplored.world.level.feature.FallenSnowTreeFeature;
import net.regions_unexplored.world.level.feature.FenCattailFeature;
import net.regions_unexplored.world.level.feature.FloorIcicleFeature;
import net.regions_unexplored.world.level.feature.GiantLilyPadFeature;
import net.regions_unexplored.world.level.feature.GlisteringIvyFeature;
import net.regions_unexplored.world.level.feature.HangingEarlightFeature;
import net.regions_unexplored.world.level.feature.HangingPrismariteFeature;
import net.regions_unexplored.world.level.feature.HyacinthPlantsFeature;
import net.regions_unexplored.world.level.feature.HyacinthStockFeature;
import net.regions_unexplored.world.level.feature.LargePointedRedstoneFeature;
import net.regions_unexplored.world.level.feature.LavaDeltaFeature;
import net.regions_unexplored.world.level.feature.LavaFallFeature;
import net.regions_unexplored.world.level.feature.MarshFeature;
import net.regions_unexplored.world.level.feature.MeadowRockFeature;
import net.regions_unexplored.world.level.feature.NetherRockFeature;
import net.regions_unexplored.world.level.feature.ObsidianSpireFeature;
import net.regions_unexplored.world.level.feature.PointedRedstoneClusterFeature;
import net.regions_unexplored.world.level.feature.PointedRedstoneFeature;
import net.regions_unexplored.world.level.feature.RockFeature;
import net.regions_unexplored.world.level.feature.RockPillarFeature;
import net.regions_unexplored.world.level.feature.SeaRockFeature;
import net.regions_unexplored.world.level.feature.ShrubFeature;
import net.regions_unexplored.world.level.feature.SmoulderingDirtFeature;
import net.regions_unexplored.world.level.feature.WaterCattailFeature;
import net.regions_unexplored.world.level.feature.WaterEdgeFeature;
import net.regions_unexplored.world.level.feature.bioshroom.GiantBlueBioshroomFeature;
import net.regions_unexplored.world.level.feature.bioshroom.GiantGreenBioshroomFeature;
import net.regions_unexplored.world.level.feature.bioshroom.GiantPinkBioshroomFeature;
import net.regions_unexplored.world.level.feature.bioshroom.GiantYellowBioshroomFeature;
import net.regions_unexplored.world.level.feature.configuration.FallenTreeConfiguration;
import net.regions_unexplored.world.level.feature.configuration.GiantBioshroomConfiguration;
import net.regions_unexplored.world.level.feature.configuration.HyacinthStockConfiguration;
import net.regions_unexplored.world.level.feature.configuration.LargePointedRedstoneConfiguration;
import net.regions_unexplored.world.level.feature.configuration.PointedRedstoneClusterConfiguration;
import net.regions_unexplored.world.level.feature.configuration.PointedRedstoneConfiguration;
import net.regions_unexplored.world.level.feature.configuration.RuTreeConfiguration;
import net.regions_unexplored.world.level.feature.configuration.SeaRockConfiguration;
import net.regions_unexplored.world.level.feature.configuration.ShrubConfiguration;
import net.regions_unexplored.world.level.feature.tree.AshenTreeFeature;
import net.regions_unexplored.world.level.feature.tree.AspenTreeFeature;
import net.regions_unexplored.world.level.feature.tree.BambooTreeFeature;
import net.regions_unexplored.world.level.feature.tree.BlackwoodTreeFeature;
import net.regions_unexplored.world.level.feature.tree.CobaltShrubFeature;
import net.regions_unexplored.world.level.feature.tree.CypressTreeFeature;
import net.regions_unexplored.world.level.feature.tree.DeadTreeFeature;
import net.regions_unexplored.world.level.feature.tree.EucalyptusTreeFeature;
import net.regions_unexplored.world.level.feature.tree.GiantCypressTreeFeature;
import net.regions_unexplored.world.level.feature.tree.IceSpireFeature;
import net.regions_unexplored.world.level.feature.tree.KapokTreeFeature;
import net.regions_unexplored.world.level.feature.tree.LarchTreeFeature;
import net.regions_unexplored.world.level.feature.tree.LargeJoshuaTreeFeature;
import net.regions_unexplored.world.level.feature.tree.LargeSocotraTreeFeature;
import net.regions_unexplored.world.level.feature.tree.LushPineTreeFeature;
import net.regions_unexplored.world.level.feature.tree.MapleTreeFeature;
import net.regions_unexplored.world.level.feature.tree.MediumJoshuaTreeFeature;
import net.regions_unexplored.world.level.feature.tree.MegaBaobabTreeFeature;
import net.regions_unexplored.world.level.feature.tree.PalmTreeFeature;
import net.regions_unexplored.world.level.feature.tree.PineTreeFeature;
import net.regions_unexplored.world.level.feature.tree.RedwoodTreeFeature;
import net.regions_unexplored.world.level.feature.tree.SaguaroCactusFeature;
import net.regions_unexplored.world.level.feature.tree.SakuraTreeFeature;
import net.regions_unexplored.world.level.feature.tree.SmallEucalyptusTreeFeature;
import net.regions_unexplored.world.level.feature.tree.SmallJoshuaTreeFeature;
import net.regions_unexplored.world.level.feature.tree.SmallOakTreeFeature;
import net.regions_unexplored.world.level.feature.tree.SmallSocotraTreeFeature;
import net.regions_unexplored.world.level.feature.tree.StrippedPineTreeFeature;
import net.regions_unexplored.world.level.feature.tree.SuperRedwoodTreeFeature;
import net.regions_unexplored.world.level.feature.tree.TreeShrubFeature;
import net.regions_unexplored.world.level.feature.tree.UltraBaobabTreeFeature;
import net.regions_unexplored.world.level.feature.tree.UltraRedwoodTreeFeature;
import net.regions_unexplored.world.level.feature.tree.YellowBioshroomShrubFeature;
import net.regions_unexplored.world.level.feature.tree.nether.BrimWillowFeature;
import net.regions_unexplored.world.level.feature.tree.nether.TallBrimWillowFeature;

public interface RUFeatureTypes {
    Supplier<Feature<GiantBioshroomConfiguration>> GIANT_BLUE_BIOSHROOM = register("giant_blue_bioshroom", new GiantBlueBioshroomFeature(GiantBioshroomConfiguration.CODEC));
    Supplier<Feature<GiantBioshroomConfiguration>> GIANT_GREEN_BIOSHROOM = register("giant_green_bioshroom", new GiantGreenBioshroomFeature(GiantBioshroomConfiguration.CODEC));
    Supplier<Feature<GiantBioshroomConfiguration>> GIANT_PINK_BIOSHROOM = register("giant_pink_bioshroom", new GiantPinkBioshroomFeature(GiantBioshroomConfiguration.CODEC));
    Supplier<Feature<GiantBioshroomConfiguration>> GIANT_YELLOW_BIOSHROOM = register("giant_yellow_bioshroom", new GiantYellowBioshroomFeature(GiantBioshroomConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> SMALL_YELLOW_BIOSHROOM = register("small_yellow_bioshroom", new YellowBioshroomShrubFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> ASHEN_TREE = register("ashen_tree", new AshenTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> ASPEN_TREE = register("aspen_tree", new AspenTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> BAMBOO_TREE = register("bamboo_tree", new BambooTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> MEGA_BAOBAB_TREE = register("mega_baobab_tree", new MegaBaobabTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> ULTRA_BAOBAB_TREE = register("ultra_baobab_tree", new UltraBaobabTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> BLACKWOOD_TREE = register("blackwood_tree", new BlackwoodTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> COBALT_TREE = register("cobalt_tree", new CobaltShrubFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> CYPRESS_TREE = register("cypress_tree", new CypressTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> DEAD_TREE = register("dead_tree", new DeadTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> SMALL_EUCALYPTUS_TREE = register("small_eucalyptus_tree", new SmallEucalyptusTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> EUCALYPTUS_TREE = register("eucalyptus_tree", new EucalyptusTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> GIANT_CYPRESS_TREE = register("giant_cypress_tree", new GiantCypressTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> LARCH_TREE = register("larch_tree", new LarchTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> LARGE_JOSHUA_TREE = register("large_joshua_tree", new LargeJoshuaTreeFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> KAPOK_TREE = register("kapok_tree", new KapokTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> MAPLE_TREE = register("maple_tree", new MapleTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> MEDIUM_JOSHUA_TREE = register("medium_joshua_tree", new MediumJoshuaTreeFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> PALM_TREE = register("palm_tree", new PalmTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> LUSH_PINE_TREE = register("lush_pine_tree", new LushPineTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> PINE_TREE = register("pine_tree", new PineTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> SMALL_JOSHUA_TREE = register("small_joshua_tree", new SmallJoshuaTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> SMALL_OAK_TREE = register("small_oak_tree", new SmallOakTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> STRIPPED_PINE_TREE = register("stripped_pine_tree", new StrippedPineTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> REDWOOD_TREE = register("redwood_tree", new RedwoodTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> SAGUARO_CACTUS = register("saguaro_cactus", new SaguaroCactusFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> SAKURA_TREE = register("sakura_tree", new SakuraTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> LARGE_SOCOTRA_TREE = register("large_socotra_tree", new LargeSocotraTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> SMALL_SOCOTRA_TREE = register("small_socotra_tree", new SmallSocotraTreeFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> SUPER_REDWOOD_TREE = register("super_redwood_tree", new SuperRedwoodTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> ULTRA_REDWOOD_TREE = register("ultra_redwood_tree", new UltraRedwoodTreeFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<PointedRedstoneConfiguration>> POINTED_REDSTONE = register("pointed_redstone", new PointedRedstoneFeature(PointedRedstoneConfiguration.CODEC));
    Supplier<Feature<LargePointedRedstoneConfiguration>> LARGE_POINTED_REDSTONE = register("large_pointed_redstone", new LargePointedRedstoneFeature(LargePointedRedstoneConfiguration.CODEC));
    Supplier<Feature<PointedRedstoneClusterConfiguration>> POINTED_REDSTONE_CLUSTER = register("pointed_redstone_cluster", new PointedRedstoneClusterFeature(PointedRedstoneClusterConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> HANGING_PRISMARITE = register("hanging_prismarite", new HangingPrismariteFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<ColumnFeatureConfiguration>> BASALT_BLOB = register("basalt_blob", new BasaltBlobFeature(ColumnFeatureConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> ASH_VENT = register("scorch_vent", new AshVentFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> LAVA_FALL = register("lava_fall", new LavaFallFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<VegetationPatchConfiguration>> OVERWORLD_LAVA_DELTA = register("overworld_lava_delta", new LavaDeltaFeature(VegetationPatchConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> BRIM_WILLOW = register("brim_willow", new BrimWillowFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> TALL_BRIM_WILLOW = register("tall_brim_willow", new TallBrimWillowFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<ShrubConfiguration>> SHRUB = register("shrub", new ShrubFeature(ShrubConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> TREE_SHRUB = register("tree_shrub", new TreeShrubFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> GIANT_LILY = register("giant_lily", new GiantLilyPadFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> ICICLE_UP = register("icicle_up", new FloorIcicleFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<MultifaceGrowthConfiguration>> AIR_MULTIFACE_GROWTH = register("air_multiface_growth", new AirMultifaceGrowthFeature(MultifaceGrowthConfiguration.CODEC));
    Supplier<Feature<FallenTreeConfiguration>> FALLEN_BLOB_TREE = register("fallen_blob_tree", new FallenBlobTreeFeature(FallenTreeConfiguration.CODEC));
    Supplier<Feature<FallenTreeConfiguration>> FALLEN_SNOW_TREE = register("fallen_snow_tree", new FallenSnowTreeFeature(FallenTreeConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> SMOULDERING_DIRT = register("smouldering_dirt", new SmoulderingDirtFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> MEADOW_ROCK = register("meadow_rock", new MeadowRockFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> ROCK = register("rock", new RockFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<RuTreeConfiguration>> SPIRE = register("spire", new IceSpireFeature(RuTreeConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> MARSH = register("marsh", new MarshFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> WATER_EDGE = register("water_edge", new WaterEdgeFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> FEN_CATTAIL = register("fen_cattail", new FenCattailFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> WATER_CATTAIL = register("water_cattail", new WaterCattailFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> ROCK_PILLAR = register("rock_pillar", new RockPillarFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<HyacinthStockConfiguration>> TALL_HYACINTH_STOCK = register("tall_hyacinth_stock", new HyacinthStockFeature(HyacinthStockConfiguration.CODEC));
    Supplier<Feature<ProbabilityFeatureConfiguration>> HYACINTH_PLANTS = register("hyacinth_plants", new HyacinthPlantsFeature(ProbabilityFeatureConfiguration.CODEC));
    Supplier<Feature<SeaRockConfiguration>> OCEAN_ROCK = register("ocean_rock", new SeaRockFeature(SeaRockConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> NETHER_ROCK = register("nether_rock", new NetherRockFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> GLISTERING_IVY = register("glistering_ivy", new GlisteringIvyFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> HANGING_EARLIGHT = register("hanging_earlight", new HangingEarlightFeature(NoneFeatureConfiguration.CODEC));
    Supplier<Feature<NoneFeatureConfiguration>> OBSIDIAN_SPIRE = register("obsidian_spire", new ObsidianSpireFeature(NoneFeatureConfiguration.CODEC));

    private static <FC extends FeatureConfiguration> Supplier<Feature<FC>> register(String name, Feature<FC> feature) {
        Registar.register(BuiltInRegistries.FEATURE, name, () -> feature);
        return () -> feature;
    }

    static void init() {
    }
}
